//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University_Final.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int ID { get; set; }
        public string Content { get; set; }
        public string VarianA { get; set; }
        public string VariantB { get; set; }
        public string VarianC { get; set; }
        public string CorrectVariant { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
